### ISSUE TITLE
Bug: Notification for logging in is incorrect

### ISSUE THREAD

**Issue by ChrisMellor** [Blooym/GoodFriend#135]
### Preflight Checklist

- [X] I have searched for existing issues and cannot find mine, or existing issues do not fit my report.

### Bug Behavior

Whenever someone logs in, the message display in the chat is as follows:

[GoodFriend] {Player Name} has logged out.

### Expected Behavior

The expected outcome is for the message logged to be

[GoodFriend] {Player Name} has logged in.

**Comment by Blooym** [comment]
Found and resolved it, thanks for the report
